### PR TITLE
Updated Website Styling

### LINKED ISSUE #1381: New website for libevent.org
Previous is not that informative, too much links one one page.
Something simple can be done with twitter boostrap, or even from existing github schemes.

This will show that the project is alive!

### PR DESCRIPTION
**Pull request by emma-coronado**
Updated the styling to modernize and improve the accessibility of the website.

### Summary of changes made:
- Integrated Bootstrap css and js framework to modernize styling and make style edits easier
- Updated Navbar and footer styling
- Improved section readability with Bootstrap card containers
- Moved internal css to new file style.css
- Cleaned up file spacing and indentation
- Moved pngs into new images file and updated corresponding references

### Notes:
No changes to content were made. These and any future styling changes made will keep all website content available, easily accessible, and simple to edit.

Fixes: https://github.com/libevent/libevent/issues/1381

### CODE REVIEW

**Review by azat — COMMENTED** [review]
Thanks a lot for you work, this is outstanding, I want this for a long long time (I've referenced the issue to this PR)!

I've reviewed it and the content is the same.

There is one tiny bit - 
libevent-web-1

Can you please adjust the authors in the footer to make each on a new line, on the left, but the note about not writing directly on the right

Thank you again!

**Comment by emma-coronado** [comment]
Glad I could help with the open issue on the other repo! I just implemented the changes you requested. Let me know what you think of the new format for the footer.  

If it's ok I plan to keep working to update and improve the styling and organization of the website. Just wanted to preliminarily submit this pull request to improve the readability of the page while it's a work in progress. Let me know if there are any changes that you think should be implemented or any styling guidelines I should adhere to.

**Comment by azat** [comment]
>Let me know what you think of the new format for the footer.

Now it is perfect, thank you!

> If it's ok I plan to keep working to update and improve the styling and organization of the website

It is more then welcome!

> Let me know if there are any changes that you think should be implemented or any styling guidelines I should adhere to.

There are couple of tiny issues, I will fix them on top
- update last modified date
- remove trailing whitespaces
- do not use backslack in path to images.

**Review by azat — APPROVED** [review]
This is astonishing! Thank you!

**Pull request merged**
